# Generated by Django 5.1.5 on 2025-01-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlyReplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Переменная')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('kaz', models.TextField(verbose_name='Казахский')),
                ('rus', models.TextField(verbose_name='Русский')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата Последнего посещения')),
            ],
            options={
                'verbose_name': 'Реплика',
                'verbose_name_plural': 'Реплики',
            },
        ),
    ]
