# Generated by Django 5.1.5 on 2025-01-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlyreplies',
            name='kaz',
            field=models.TextField(verbose_name='текст на Казахском'),
        ),
        migrations.AlterField(
            model_name='onlyreplies',
            name='rus',
            field=models.TextField(verbose_name='текст на Русском'),
        ),
    ]
