# Generated by Django 5.1.5 on 2025-01-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0002_alter_onlyreplies_kaz_alter_onlyreplies_rus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlyreplies',
            name='description',
            field=models.CharField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='onlyreplies',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Переменная'),
        ),
    ]
