# Generated by Django 5.1.5 on 2025-01-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0003_alter_onlyreplies_description_alter_onlyreplies_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlyreplies',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
