version: '3.9'
services:
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - static_volume:/var/www/static/
      - media_volume:/var/www/media/
      - ./nginx.conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:80:80"
    networks:
      - battery_battery-net
  web:
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn fusion_core.wsgi:application --bind 0.0.0.0:8000 --workers 2
      "
    build: .
    volumes:
      - .:/app
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - battery_battery-net
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - battery_battery-net
  redis:
    image: redis:latest
    networks:
      - battery_battery-net
  celery:
    build: .
    command: celery -A fusion_core worker -l info --concurrency=3
    volumes:
      - ./errorlogs:/app/errorlogs
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - .:/app
    networks:
      - battery_battery-net
    depends_on:
      - web
  celery-beat:
    build: .
    volumes:
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - .:/app
      - ./errorlogs:/app/errorlogs
    command: celery -A fusion_core beat -l info
    networks:
      - battery_battery-net
    depends_on:
      - web
volumes:
  db_data:
  static_volume:
  media_volume:
networks:
  battery_battery-net:
    external: true

