# Generated by Django 5.1.5 on 2025-01-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={},
        ),
    ]