# Generated by Django 5.1.5 on 2025-01-23 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_usertelegram_phone_from_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user_telegram',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.usertelegram', verbose_name='Телеграм Пользователь'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_watsapp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.userwhatsapp', verbose_name='Вотсапп Пользователь'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user_telegram',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.usertelegram', verbose_name='Телеграм Пользователь'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user_watsapp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.userwhatsapp', verbose_name='Вотсапп Пользователь'),
        ),
    ]