# Generated by Django 5.1.5 on 2025-01-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_client_user_telegram_alter_client_user_watsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Язык'),
        ),
    ]