# Generated by Django 5.1.5 on 2025-02-06 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_clientprofile_contact_email_and_more'),
        ('lottery', '0009_lotteryclients_lotterysellers_battery_is_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_winner',
            field=models.BooleanField(default=False, verbose_name='Победитель'),
        ),
        migrations.AddField(
            model_name='client',
            name='lottery_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lottery.lotteryclients', verbose_name='Победитель'),
        ),
        migrations.AddField(
            model_name='client',
            name='present_type',
            field=models.CharField(blank=True, choices=[('little', '25000'), ('big', '50000')], max_length=255, null=True, verbose_name='Тип приза'),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_winner',
            field=models.BooleanField(default=False, verbose_name='Победитель'),
        ),
        migrations.AddField(
            model_name='seller',
            name='lottery_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lottery.lotterysellers', verbose_name='Победитель'),
        ),
        migrations.AddField(
            model_name='seller',
            name='present_type',
            field=models.CharField(blank=True, choices=[('little', '25000')], max_length=255, null=True, verbose_name='Тип приза'),
        ),
    ]
