# Generated by Django 5.1.5 on 2025-02-06 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_client_is_winner_client_lottery_winner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_winner',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_winner',
        ),
    ]
