# Generated by Django 5.1.5 on 2025-02-07 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_remove_client_is_winner_remove_seller_is_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='bot.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to='bot.seller', verbose_name='Продавец'),
        ),
    ]
