# Generated by Django 5.1.5 on 2025-02-07 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_clientprofile_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clientprofile', to='bot.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sellerprofile', to='bot.seller', verbose_name='Продавец'),
        ),
    ]
