# Generated by Django 5.1.5 on 2025-02-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_client_options_alter_seller_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Продавец', 'verbose_name_plural': 'Продавцы'},
        ),
    ]
