# Generated by Django 5.1.5 on 2025-02-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_seller_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='present_type',
            field=models.CharField(blank=True, choices=[('25000', '25000'), ('50000', '50000'), ('100000', '100000')], max_length=255, null=True, verbose_name='Тип приза'),
        ),
    ]
