# Generated by Django 5.1.5 on 2025-02-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_alter_client_present_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='contact_email',
            field=models.CharField(blank=True, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='contact_email',
            field=models.CharField(blank=True, null=True, verbose_name='Город'),
        ),
    ]
