# Generated by Django 5.1.5 on 2025-03-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_alter_clientprofile_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='present_type',
            field=models.CharField(blank=True, choices=[('25000', '25000'), ('1000000', '1000000')], max_length=255, null=True, verbose_name='Тип приза'),
        ),
    ]
