# Generated by Django 5.1.5 on 2025-01-29 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0006_clientprofile_language_sellerprofile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=255, unique=True, verbose_name='Серийный номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('confirmation_code', models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Код для продавца')),
                ('tech_message', models.TextField(blank=True, null=True, verbose_name='Техническое сообщение')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.client', verbose_name='Клиент')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.seller', verbose_name='Продавец')),
            ],
        ),
    ]
