# Generated by Django 5.1.5 on 2025-01-29 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_clientprofile_language_sellerprofile_language'),
        ('lottery', '0002_alter_battery_latitude_alter_battery_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True, verbose_name='Ввод')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.usertelegram', verbose_name='Телеграм Пользователь')),
            ],
        ),
    ]
