# Generated by Django 5.1.5 on 2025-01-29 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_invalidtry'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='invoice_telegram_id',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Чек'),
        ),
        migrations.CreateModel(
            name='InvoicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='invoice_photos/', verbose_name='Фото чека')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.battery', verbose_name='Аккумулятор')),
            ],
        ),
    ]
