# Generated by Django 5.1.5 on 2025-01-30 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_clientprofile_language_sellerprofile_language'),
        ('lottery', '0005_alter_battery_invoice_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('telegram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.usertelegram', verbose_name='Клиент')),
            ],
        ),
    ]
