# Generated by Django 5.1.5 on 2025-02-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0007_telegrammessage_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=50, unique=True, verbose_name='Название шаблона')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
        ),
    ]
