# Generated by Django 5.1.5 on 2025-02-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0008_messagetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Розыгрыш')),
                ('little_prize', models.IntegerField(verbose_name='Количество призов 25000')),
                ('big_prize', models.IntegerField(verbose_name='Количество призов 50000')),
                ('report', models.TextField(blank=True, null=True, verbose_name='Отчет о розыгрыше')),
            ],
            options={
                'verbose_name': 'Розыгрыш среди клиентов',
                'verbose_name_plural': 'Розыгрыши среди клиентов',
            },
        ),
        migrations.CreateModel(
            name='LotterySellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Розыгрыш')),
                ('little_prize', models.IntegerField(verbose_name='Количество призов 25000')),
                ('report', models.TextField(blank=True, null=True, verbose_name='Отчет о розыгрыше')),
            ],
            options={
                'verbose_name': 'Розыгрыш среди продавцов',
                'verbose_name_plural': 'Розыгрыши среди продавцов',
            },
        ),
        migrations.AddField(
            model_name='battery',
            name='is_winner',
            field=models.BooleanField(default=False, verbose_name='Победитель'),
        ),
    ]
