# Generated by Django 5.1.5 on 2025-02-06 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0009_lotteryclients_lotterysellers_battery_is_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='is_winner',
        ),
    ]
