# Generated by Django 5.1.5 on 2025-02-07 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0013_alter_battery_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicephoto',
            name='battery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_photo', to='lottery.battery', verbose_name='Аккумулятор'),
        ),
    ]
