# Generated by Django 5.1.5 on 2025-02-11 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_seller_options'),
        ('lottery', '0014_alter_invoicephoto_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battery', to='bot.seller', verbose_name='Продавец'),
        ),
    ]
