# Generated by Django 5.1.5 on 2025-02-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0015_alter_battery_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryclients',
            name='super_prize',
            field=models.BooleanField(default=False, verbose_name='Розыгрыш 1000000 (если активно разыгрывается среди клиентов зарегистрировавших хотя бы один аккумулятор'),
        ),
    ]
