# Generated by Django 5.1.5 on 2025-02-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0016_lotteryclients_super_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryclients',
            name='super_prize',
            field=models.IntegerField(default=None, verbose_name='Розыгрыш 1000000'),
        ),
    ]
