# Generated by Django 5.1.5 on 2025-02-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0017_alter_lotteryclients_super_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryclients',
            name='super_prize',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Розыгрыш 1000000'),
        ),
    ]
