# Generated by Django 5.1.5 on 2025-03-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0018_alter_lotteryclients_super_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotterysellers',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отсечки. Для приоритета новых продавцов'),
        ),
    ]
