# Generated by Django 5.1.5 on 2025-03-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0019_lotterysellers_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotterysellers',
            name='super_prize',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Розыгрыш 1000000'),
        ),
    ]
