# Generated by Django 5.1.5 on 2025-04-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0020_lotterysellers_super_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotterysellers',
            name='little_prize',
            field=models.IntegerField(default=1, verbose_name='Количество призов 25000'),
        ),
    ]
